"""init migration3

Revision ID: 179cb8bef9dd
Revises: 52c257c82e6a
Create Date: 2023-07-05 00:46:27.628928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '179cb8bef9dd'
down_revision = '52c257c82e6a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
