"""init migration2

Revision ID: 52c257c82e6a
Revises: da09ce017228
Create Date: 2023-07-05 00:44:48.262548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52c257c82e6a'
down_revision = 'da09ce017228'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
