"""init migration1

Revision ID: da09ce017228
Revises: 
Create Date: 2023-07-05 00:34:05.193965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da09ce017228'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_name', sa.String(length=5), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Lecturers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lecturer_name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Disciplines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('discipline_name', sa.String(length=15), nullable=False),
    sa.Column('lecturer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lecturer_id'], ['Lecturers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Students',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_name', sa.String(length=30), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['Groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('discipline_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['discipline_id'], ['Disciplines.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['Students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Scores')
    op.drop_table('Students')
    op.drop_table('Disciplines')
    op.drop_table('Lecturers')
    op.drop_table('Groups')
    # ### end Alembic commands ###
