# Generated by Django 4.2.3 on 2023-07-12 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_tag_remove_quote_tags_quote_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='author',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='tags',
        ),
    ]
