# Generated by Django 4.2.3 on 2023-07-12 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_remove_quote_author_remove_quote_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='author_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='quotes.author'),
        ),
    ]
