# Generated by Django 4.2.3 on 2023-07-12 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0007_alter_tag_tag_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='tags',
        ),
    ]
